"""empty message

Revision ID: 4122be7355a5
Revises: None
Create Date: 2014-10-04 21:05:22.019119

"""

# revision identifiers, used by Alembic.
revision = '4122be7355a5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
